version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:latest
    steps:
      - run: echo "build"
  test:
    docker:
      - image: circleci/clojure:latest
    steps:
      - run: exit $(($RANDOM%2))
  scan:
    docker:
      - image: circleci/clojure:latest
    steps:
      - run: echo "more more test blah"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
  security_scan:
    jobs:
      - build
      - scan